kind: pipeline
type: docker
name: default

steps:
- name: lint-code
  image: golang:alpine
  environment:
    GOLINTCI_VERSION: v1.50.1
    CGO_ENABLED: 0
    GOOS: linux
  commands:
  - go version
  - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLINTCI_VERSION}
  - golangci-lint --version
  - golangci-lint run ./...
  failure: ignore
  volumes:
  - name: deps
    path: /go

- name: build-code
  image: golang:alpine
  environment:
    CGO_ENABLED: 1
    GOOS: linux
  commands:
  - apk add tesseract-ocr
  - tesseract --version
  - go build -a -installsuffix cgo -o wbar
  volumes:
  - name: deps
    path: /go
  when:
    ref:
    - refs/tags/*
  depends_on:
  - lint-code

volumes:
- name: deps
  temp: {}
